enum DErrorComponent { Server, SDK, Database }

enum DErrorCode {
  ALREADY_AUTHENTICATED,
  API_UNSUCCESSFUL_RESPONSE,
  API_RESPONSE_PROCESS_ERROR,
  APP_NAME_NOT_SET,
  APP_VERSION_NOT_SET,
  BAD_CREDENTIALS,
  CANT_CREATE_EXISTING_OBJECT,
  CANT_DELETE_NON_EXISTING_OBJECT,
  LOGIN_USERNAME_NULL,
  LOGIN_PASSWORD_NULL,
  NO_AUTHENTICATED_USER,
  NO_AUTHENTICATED_USER_OFFLINE,
  NO_RESERVED_VALUES,
  OBJECT_CANT_BE_UPDATED,
  OBJECT_CANT_BE_INSERTED,
  OBJECT_ACCESS_DENIED,
  OBJECT_ACCESS_CLOSED,
  SERVER_URL_NULL,
  SERVER_URL_MALFORMED,
  SOCKET_TIMEOUT,
  UNEXPECTED,
  UNKNOWN_HOST,
  URL_NOT_FOUND,
  USER_ACCOUNT_DISABLED,
  USER_ACCOUNT_LOCKED
}
